stage('test[unit&quality]') {
    parallel 'unit-test': {
        node {
            unstash 'source'
            sh 'mvn -Dmaven.test.failure.ignore=true test'
            step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
            if(currentBuild.result == 'UNSTABLE'){
                error "Unit test failures"
            }
        }
    }
  }